version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_test_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  node_app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres